sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-044
env:
  global:
    -
      # LTD_AWS_ID
      secure: tCXVJIDuJujI4y1FhGrSljcASXoD6CSzI3Xq47FlXTGMJuRMgM1UaWQs8Rnw5VpKUyLr+mtzpptBY0Aize2YAYhUD68AAgl6lvpdWcuTPzcFgFFhFnf56ewnywkkYcpjOX6e+oW8f99XJLZ9N6zO+tiDelB4gHLrHBWmWj0STcl14+ywU1bZZuRwVLIv7xlrHqQo3nKgDhVhtOxLsKOrfw8CMIB1c7Zmzopl6LJB/HvHEwn7AZjPgCsAMEcM4wjCUEZcsdf5cxn3zcOcJ6frlio/A0KY4VDI91aNdolPzk1dEbbN3142rE4LYi+ofED3QeHZepd7Zq5IC3q11RaIwHeNe21dD1DGsckSlWQNVch/HHqM70gpW4YoQQFyrkRPgUYv2XlGkrX+jb+x3C1q3M003FCpBuuwbGm96mBBk9XWGGqO8k3jz8fQSZhRL6oTnAUgioXGEjPpGSXAKWt6u2E5sEU1Qthlu4xjQecpMHwz9KLOkjbxFoN+DbUvO+rogU3/gdMp/MS0T/yrL/ruZLef8IWzml2ZOAXT0r4lY65y5L/c2lqAiwKytGm9y2OfbU0WLe+2EsRk7+Tj5aUrncYtoyKlMCt2LlW0SNFiICIohhayevZepE6dgJR54OikzY5+oKNx+I6Gv64EYZVKV09ZojS8fN91Q2m2M//IBhU=
    -
      # LTD_AWS_SECRET
      secure: E5Pv7Qr+YRiJGvYC9sBs/lpF8/nwsDaqlVIua6KVmA67GYDDgVLSbT5pVEzCmZ/x3MjrJQvhsQcRUW0hBSuaXCZPbsc4d0kIeCwhq/oeLA9etbWyd6wuAcitSEx5B6ta+8OJ//fk536hVrhSeJb9QOLgZTex+SzKZrmhMSy46n1WNs0Prri9s4MkOtxhRt/OR2E+Kbc1kzv9QRd4LpabSROU7XBJb2suae+YQmZZh63cpniOOWuK3oS52ZxT5mc8PS3RxkTTXGVXGXOoMjTWnSC5+8VY6xgEzFfZKSFH/syDXS8Mg4j0i8DV/uku5udYf0xi5Bo10dYepYa15TkmvEdp2DqCrIIy/u22n1wkKcLGLf2qyD86d+00A1cjSbrDehEcnBYLAwZCbvdteJzfzYDJ8WqFSyZkaKu15E8WtDmtu8gaQij3RRqwcO9H8rP7mvM1qvPzap5/zSF0gW+59OgaOxiE1Cdt/3SmwRRrKpCE7M0SNEsmU1C9KcgkdBSuV21E6JLc0iGDlV3jhPaXR67K0kaDT0AxUFU5wgKLzGRxBv9Q18RcqxOQJFN56XKsk/zsUF/V+JU2ZyDk++7Z7LNA0VfzkwKhlOzCVd9w6/oC8Q1+YqTzkn3zuWQyQj6WP7Aqn4FWGaNqpSP/odd0uYOot5bNENHTpwANdLUD7UY=
    -
      # LTD_USERNAME
      secure: aXXFDMSHsulZsU6nupwJ0yjb/yCLtc9X4zAAdWYvIJH+I68oezM6WdxGPIxcEVw/J51N3ePiiKbRBzkGwFQhm28N/mtMhxwWBwmiSa5DhZoN3oLLlnacmEdPYgswgD+DDzdCCLOjEckvC0yg0JPpY3J02ez7BU77gxl2kVvCkpSqVoxzwO1s239ap2ktfInSWJd421V5aGr0i1oMF+wIs9+cwoEEtD4a1o9kCqx3PfwOpSOur1oy6yK8mx5uG3Wl3GyzNPCl8dhglzWeHZYcZyI2zi8tm672GtBMtKsxzeOoZpwcXTOgKbFXtfsvISQvW96gapYOdq9wmf8vUbnYGGc+T+ZARsFpF2XnvtwiePtMelArOm7jJvG7NovlmLciNb9cQyKJM2PyZDN5knEJEKaNLJ1i/4mDOilZUp/C1HD4j0bb0UjaSIDQEXq3J+YHE68rhsOEWKjjnYHim06a9QLMZYdTu01PzQ4F7rpbReMrWrEnYXzt3SSxWvl4dYGA1uEW8uDtgXyiGixm8xgfc3hT97+45JeH8DMU40MON5/ncVAqCYn9BLsWzRR+wgWsVXkTlm7xWaZNwOtRYb/bi9b5VnjOXH3EBQDlymEnOpfrsf6BxPIqNQAolRjBptNaaIiD7vz34Ay+SHsDmdAjHQXVJDHthc/6IbgYF4ncIn4=
    -
      # LTD_PASSWORD
      secure: cubrwHbBbib58/s5t/uKdryUrxwAIIeMAyT6mGRhddSW/z+ef4CK94Qjy2qcx5f/cjW+T61orZwMCcH64IMJXCC/2ur6OARFyJ9v4afBj6617epwl8h0DwvLasOL7018RHWKNBJTqfIYwGr7oUHVhmVNx3opzQJsq/Rr4W7yZlOEEMohbGVbhxqnjOW64k8mjcBrx5wnGNu031dCZIfFfkcwEh8FeGBJVR/nmcq3Q3L10jtTClCeRruefnF8WXmB2gHnH0gMBBTvlowHwua2UsVJAIb0ese1VpJ6wrVFKqruGoSu7ee1EmPitePfNgYj71Kr2l0n27TMEBzX11Rl3AzevrL5mkJzgIzOl2WKdKIMQTZL/wzGGBQ0B4PayfdVky3moExCmvzJiDFyslxJ2S4UIXig9f8jOeaFZ8KXGD0avbU+1z4PvaQDDSM+tqZHYwK655Wicy4fCcQwsCLmkwFZKcRGHqRKyPBchwZJtTYwIQvaIUhitcp9boErHqa95MNO1W4LiNDQ9+ZP/tlbADbAa9ZRHqd0psicV5qWl0riOSktAVx5fn+Ou9CrC9lp8itbXBu9Bdi9jXoiS+mOvfpBQtDqBwqLAEGEdIYJlToQTfJ63z/1ZN/32ueQZObRvE0P/k08XFcmquP+0lwofIw1SccJkKk1phQLHUUsXMA=
